kind: pipeline
name: tc_build

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: default
    image: wloot/tcbuild:latest
    environment:
      GITID:
        from_secret: git_id
      GITPWD:
        from_secret: git_password
    commands:
      - git config --global user.email "wlootlxt123@gmail.com"
      - git config --global user.name "Julian Liu"
      - bash ./.ci/env-setup.sh
      - bash ./.ci/build.sh
